version: '3.8'
services:
  auth-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_Token: "fgrejegoiergjio"
      LOCAL_SERVER_PORT: ":8080"
    volumes:
      - ./config.yaml:/root/config.yaml
